package me.s17339.memorygame.resinfo;

public enum LanguageNode {
	GENERAL_LANGUAGENAME("GENERAL.LanguageName"),
	GENERAL_RETURNBUTTON("GENERAL.ReturnButton"),
	
	MENU_TITLE("MENU.Title"),
	MENU_SUBTITLE("MENU.Subtitle"),
	MENU_NEWGAME("MENU.NewGame"),
	MENU_CREDITS("MENU.Credits"),
	MENU_HIGHSCORES("MENU.HighScores"),
	MENU_SETTINGS("MENU.Settings"),
	MENU_QUIT("MENU.Quit"),
	
	CREDITS_TITLE("CREDITS.Title"),
	CREDITS_DEVELOPERS("CREDITS.Developers"),
	CREDITS_SOUNDS("CREDITS.Sounds"),
	CREDITS_SONGS("CREDITS.Songs"),
	CREDITS_IMAGES("CREDITS.Images"),

	SETTINGS_TITLE("SETTINGS.Title"),
	SETTINGS_SOUNDSVOLUME("SETTINGS.SoundsVolume"),
	SETTINGS_SONGSVOLUME("SETTINGS.SongsVolume"),
	SETTINGS_UNREVEALINGALLOWED("SETTINGS.UnrevealingAllowed"),
	SETTINGS_HIDEONCOLLECT("SETTINGS.HideOnCollect"),
	SETTINGS_LANGUAGE("SETTINGS.Language"),

	INGAME_PRESSTOSTART("INGAME.PressToStart"),
	INGAME_TIME("INGAME.Time"),
	INGAME_PAUSED("INGAME.Paused"),
	INGAME_RAGEQUIT("INGAME.Ragequit"),
	
	DIFFICULTYCHOOSING_TITLE("DIFFICULTYCHOOSING.Title"),
	DIFFICULTYCHOOSING_SUBTITLE("DIFFICULTYCHOOSING.Subtitle"),
	DIFFICULTYCHOOSING_LEVEL_ALZHEIMER("DIFFICULTYCHOOSING.Level.Alzheimer"),
	DIFFICULTYCHOOSING_LEVEL_EASY("DIFFICULTYCHOOSING.Level.Easy"),
	DIFFICULTYCHOOSING_LEVEL_MODERATE("DIFFICULTYCHOOSING.Level.Moderate"),
	DIFFICULTYCHOOSING_LEVEL_CHALLENGING("DIFFICULTYCHOOSING.Level.Challenging"),
	DIFFICULTYCHOOSING_TOOLTIP_LEVEL_ALZHEIMER("DIFFICULTYCHOOSING.TOOLTIP.Level.Alzheimer"),
	DIFFICULTYCHOOSING_TOOLTIP_LEVEL_EASY("DIFFICULTYCHOOSING.TOOLTIP.Level.Easy"),
	DIFFICULTYCHOOSING_TOOLTIP_LEVEL_MODERATE("DIFFICULTYCHOOSING.TOOLTIP.Level.Moderate"),
	DIFFICULTYCHOOSING_TOOLTIP_LEVEL_CHALLENGING("DIFFICULTYCHOOSING.TOOLTIP.Level.Challenging"),
	
	HIGHSCORES_TITLE("HIGHSCORES.Title"),
	HIGHSCORES_CHOOSE_LEVEL("HIGHSCORES.ChooseLevel"),
	HIGHSCORES_LEVEL_ALZHEIMER("HIGHSCORES.Level.Alzheimer"),
	HIGHSCORES_LEVEL_EASY("HIGHSCORES.Level.Easy"),
	HIGHSCORES_LEVEL_MODERATE("HIGHSCORES.Level.Moderate"),
	HIGHSCORES_LEVEL_CHALLENGING("HIGHSCORES.Level.Challenging"),
	HIGHSCORES_TYPING("HIGHSCORES.Typing"),
	HIGHSCORES_NO_DATA("HIGHSCORES.NoData"),
	HIGHSCORES_COLUMN_PLACE("HIGHSCORES.Column.Place"),
	HIGHSCORES_COLUMN_NICKNAME("HIGHSCORES.Column.Nickname"),
	HIGHSCORES_COLUMN_RESULT("HIGHSCORES.Column.Result");

	private String path;
	private LanguageNode(String path) {
		this.path = path;
	}
	
	public String getPath() {
		return path;
	}
}